import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import logging
from config import EMAIL_USER, EMAIL_PASS, EMAIL_TO
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

logger = logging.getLogger(__name__)


def format_html_email(use_cases, product_ideas=None):
    """Create nicely formatted HTML email"""
    html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 900px; margin: 0 auto; }}
            .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 8px 8px 0 0; text-align: center; }}
            .summary {{ background: #f8f9fa; padding: 20px; margin: 20px 0; border-left: 4px solid #667eea; }}
            .section-title {{ background: #667eea; color: white; padding: 15px; margin: 30px 0 20px 0; border-radius: 6px; font-size: 20px; font-weight: bold; }}
            .product-idea {{ background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%); padding: 25px; margin: 20px 0; border: 2px solid #667eea; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }}
            .product-idea h3 {{ margin: 0 0 10px 0; color: #667eea; font-size: 22px; }}
            .product-tagline {{ font-style: italic; color: #555; margin-bottom: 15px; }}
            .product-detail {{ margin: 10px 0; padding: 8px; background: white; border-radius: 4px; }}
            .detail-label {{ font-weight: bold; color: #667eea; display: inline-block; width: 130px; }}
            .use-case {{ background: white; padding: 20px; margin: 15px 0; border: 1px solid #e0e0e0; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
            .use-case h3 {{ margin: 0 0 15px 0; color: #764ba2; font-size: 18px; }}
            .detail {{ margin: 8px 0; padding-left: 10px; }}
            .label {{ font-weight: bold; color: #555; }}
            .footer {{ margin-top: 40px; padding-top: 20px; border-top: 2px solid #e0e0e0; color: #777; font-size: 12px; text-align: center; }}
            .badge {{ display: inline-block; padding: 4px 12px; border-radius: 12px; font-size: 12px; font-weight: bold; margin: 5px 5px 5px 0; }}
            .badge-easy {{ background: #d4edda; color: #155724; }}
            .badge-medium {{ background: #fff3cd; color: #856404; }}
            .badge-hard {{ background: #f8d7da; color: #721c24; }}
            ul {{ margin: 5px 0; padding-left: 20px; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1 style="margin: 0;">🚀 Daily AI Business Intelligence</h1>
            <p style="margin: 10px 0 0 0;">Product Ideas + Use Cases from Today's AI News</p>
        </div>
        
        <div class="summary">
            <strong>📊 Today's Summary:</strong><br>
            ✅ Found <strong>{len(use_cases)}</strong> AI use cases<br>
            {'✅ Generated <strong>' + str(len(product_ideas)) + '</strong> product ideas<br>' if product_ideas else ''}
        </div>
    """
    
    # Product Ideas Section (Updated to handle list of strings)
    if product_ideas and len(product_ideas) > 0:
        html += '<div class="section-title">💡 PRODUCT IDEAS YOU CAN BUILD</div>'
        
        for i, idea_str in enumerate(product_ideas, 1): # Iterate over strings directly
            # Since product_ideas is now a list of strings, we cannot extract structured data.
            # We will display the raw string as the idea.
            html += f"""
            <div class="product-idea">
                <h3>💡 {i}. {idea_str}</h3>
                <!-- Note: Specific details like difficulty, target market, etc., are not available for raw strings -->
            </div>
            """
    
    # Use Cases Section (Keep original logic for use_cases dicts)
    html += '<div class="section-title">📋 TODAY\'S AI USE CASES</div>'
    
    for i, uc in enumerate(use_cases, 1):
        html += f"""
        <div class="use-case">
            <h3>{i}. {uc.get('product', 'Unknown Product')}</h3>
            <div class="detail">
                <span class="label">📋 Use Case:</span> {uc.get('use_case', 'N/A')}
            </div>
            <div class="detail">
                <span class="label">🏢 Industry:</span> {uc.get('industry', 'Not specified')}
            </div>
            <div class="detail">
                <span class="label">✨ Benefit:</span> {uc.get('benefit', 'Not specified')}
            </div>
        </div>
        """
    
    html += """
        <div class="footer">
            <p>🤖 Generated by AI News Agent | Powered by Ollama (Local AI)</p>
            <p>This report analyzes today's AI news to extract actionable business opportunities</p>
        </div>
    </body>
    </html>
    """
    return html


def format_plain_text(use_cases, product_ideas=None):
    """Create plain text version of email"""
    body = "=" * 70 + "\n"
    body += "DAILY AI BUSINESS INTELLIGENCE\n"
    body += "=" * 70 + "\n\n"
    body += f"Found {len(use_cases)} use cases from today's AI news\n"
    if product_ideas:
        body += f"Generated {len(product_ideas)} product ideas\n"
    body += "\n"
    
    # Product Ideas (Updated to handle list of strings)
    if product_ideas and len(product_ideas) > 0:
        body += "=" * 70 + "\n"
        body += "PRODUCT IDEAS YOU CAN BUILD\n"
        body += "=" * 70 + "\n\n"
        
        for i, idea_str in enumerate(product_ideas, 1): # Iterate over strings directly
            body += f"{i}. {idea_str}\n" # Print the raw string
            body += "-" * 70 + "\n" # Separator
            # Note: Specific details like difficulty, target market, etc., are not available for raw strings
            body += "\n"
    
    # Use Cases (Keep original logic for use_cases dicts)
    body += "=" * 70 + "\n"
    body += "TODAY'S AI USE CASES\n"
    body += "=" * 70 + "\n\n"
    
    for i, uc in enumerate(use_cases, 1):
        body += f"{i}. {uc.get('product', 'Unknown Product')}\n"
        body += "-" * 70 + "\n"
        body += f"   Use Case: {uc.get('use_case', 'N/A')}\n"
        body += f"   Industry: {uc.get('industry', 'Not specified')}\n"
        body += f"   Benefit: {uc.get('benefit', 'Not specified')}\n\n"
    
    body += "=" * 70 + "\n"
    body += "Generated by AI News Agent | Powered by Ollama (Local AI)\n"
    
    return body


def send_email_notification(use_cases, product_ideas=None):
    """Send use cases and product ideas via email"""
    if not all([EMAIL_USER, EMAIL_PASS, EMAIL_TO]):
        logger.error("Email settings not configured")
        return False
    
    if not use_cases:
        logger.warning("No use cases to send")
        return False
    
    try:
        recipients = [email.strip() for email in EMAIL_TO.split(',')]
        logger.info(f"Sending to {len(recipients)} recipients")
        
        msg = MIMEMultipart('alternative')
        ideas_count = len(product_ideas) if product_ideas else 0
        msg['Subject'] = f"🚀 Daily AI Intelligence - {len(use_cases)} Use Cases + {ideas_count} Product Ideas"
        msg['From'] = EMAIL_USER
        msg['To'] = ', '.join(recipients)
        
        plain_text = format_plain_text(use_cases, product_ideas)
        html_text = format_html_email(use_cases, product_ideas)
        
        part1 = MIMEText(plain_text, 'plain')
        part2 = MIMEText(html_text, 'html')
        
        msg.attach(part1)
        msg.attach(part2)
        
        logger.info("Connecting to SMTP server...")
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(EMAIL_USER, EMAIL_PASS)
        server.send_message(msg)
        server.quit()
        
        logger.info(f"✅ Email sent successfully to {len(recipients)} recipients")
        return True
        
    except Exception as e:
        logger.error(f"Error sending email: {e}")
        return False


def send_error_notification(articles):
    """Send email when agent runs but finds no use cases"""
    if not all([EMAIL_USER, EMAIL_PASS, EMAIL_TO]):
        return False
    
    try:
        recipients = [email.strip() for email in EMAIL_TO.split(',')]
        
        msg = MIMEMultipart('alternative')
        msg['Subject'] = "⚠️ AI News Agent - No Data Found"
        msg['From'] = EMAIL_USER
        msg['To'] = ', '.join(recipients)
        
        plain_text = f"""
AI News Agent Report
{"="*60}

⚠️ WARNING: No use cases were extracted today

Articles Scraped: {len(articles)}
Use Cases Found: 0

Please check if Ollama is running ('ollama serve')
"""
        
        html_text = f"""
        <html>
        <body style="font-family: Arial;">
            <div style="background: #dc3545; color: white; padding: 20px;">
                <h1>⚠️ AI News Agent Alert</h1>
            </div>
            <div style="padding: 20px;">
                <p><strong>Articles Scraped:</strong> {len(articles)}</p>
                <p><strong>Use Cases Found:</strong> 0</p>
                <p>Please check if Ollama is running</p>
            </div>
        </body>
        </html>
        """
        
        msg.attach(MIMEText(plain_text, 'plain'))
        msg.attach(MIMEText(html_text, 'html'))
        
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(EMAIL_USER, EMAIL_PASS)
        server.send_message(msg)
        server.quit()
        
        logger.info("Error notification sent")
        return True
        
    except Exception as e:
        logger.error(f"Error sending notification: {e}")
        return False
